%YAML 1.2
---
imports:
  - resource: elastic.yml
  - resource: ../package.json
    pick:
      name: app.name
      version: app.version

parameters:
    ISTEX_SESSION: DEFAULT_SESSION

currentSessionName: %env(ISTEX_SESSION)%
