%YAML 1.2
---
imports:
  - resource: config.yml

elastic:
  indices:
    documents:
         index: co-deduplicate-integration-test
         aliases: %toDeduplicateMapping%

deduplicate:
  target: co-deduplicate-integration-test

currentSessionName: TEST_SESSION
