%YAML 1.2
---

imports:
  - resource: ../node_modules/corhal-config/index.js
    pick:
        elastic.nodes: parameters.nodes
        elastic.authUsername: parameters.authUsername
        elastic.authPassword: parameters.authPassword
        elastic.aliasesMapping.TO_DEDUPLICATE: parameters.toDeduplicateMapping
        elastic.aliases.TO_DEDUPLICATE: parameters.CO_DEDUPLICATE_ES_TARGET



elastic:
  clients:
    default:
      nodes: %nodes% # string | string[]
      auth:
        username: %authUsername%
        password: %authPassword%
      ssl:
        rejectUnauthorized: false
      sniffOnStart: true
  indices:
    documents:
         index: ~ # string - The name of the index
         aliases: ~ # object of objects - Aliases for the index

deduplicate:
    target: %env(CO_DEDUPLICATE_ES_TARGET)% # Comma-separated list of data streams, indices, and aliases to search.
